name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     
     - name: Start SSH via Ngrok
       env:
        NGROK_TOKEN: 1ZpjOz80nCmu1JfWEaSBeDtA6Bi_3pCPgRPJGgRZSa6dfHgY4
        USER_PASS: Aa123456
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       
     - name: Run Start Script
       env:
        NGROK_TOKEN: 1ZpjOz80nCmu1JfWEaSBeDtA6Bi_3pCPgRPJGgRZSa6dfHgY4
       run: source ubuntu-start.sh &&  sleep 6h 
       
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 6h   
       
     - name: Don't kill instace2
       run: sleep 1s   
