# https://github.com/P3TERX/ActionsVM

name: Ubuntu (tmate)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Start SSH via tmate
      uses: P3TERX/ssh2actions@main
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Don't kill instace
      if: ${{ failure() }}
      run: sleep 6h
       
    - name: Run Start Script
      run: source ubuntu-start.sh

    - name: Run End Script
      run: source ubuntu-end.sh
      
    - name: tar my file
      id: tar
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        echo "FILEPATH=$PWD" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV
        tar -xzvf ${{ env.FILEPATH }}/../File_${{ env.FILE_DATE }}.tar.gz ./
        rm -rf ./
        echo "::set-output name=status::success"
          
    - name: Upload file to Release
      id: release
      uses: ncipollo/release-action@v1
      if: steps.rebuild.outputs.status == 'success' && !cancelled()
      with:
        tag: ../File_${{ env.FILE_DATE }}
        artifacts: ${{ env.FILEPATH }}/../*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          This is myfile
          
    - name: Don't kill instace
      if: ${{ failure() }}
      run: sleep 6h